[workspace]
members = ["walkers", "demo", "demo_native", "demo_web"]

[workspace.package]
version = "0.13.0"

[workspace.dependencies]
image = "0.24"
log = "0.4"
egui = ">=0.23,<=0.24"
egui_extras = { version = ">=0.23,<=0.24", features = ["svg"] }
eframe = ">=0.23,<=0.24"
